### ISSUE TITLE
AssertionError: Test case is leaking async ops.

### ISSUE THREAD

**Issue by viztastic** [asos-craigmorten/superoak#6]
# Issue
![image](https://user-images.githubusercontent.com/8556736/85203067-5b5f1380-b34e-11ea-97fd-61ae0a581130.png)

Setup:
```
deno 1.1.0
v8 8.4.300
typescript 3.9.2
oak version: v5.3.0
```

Getting the following error (screenshot above)

```
AssertionError: Test case is leaking async ops.
Before:
  - dispatched: 7
  - completed: 6
After:
  - dispatched: 23
  - completed: 23
```

Am I meant to chain a `.end()` to the last request in each test file?
